FROM almalinux:9
ENV Course="Devops" \
    Duration="120hr" 
ARG Trainer="Sivakumar"
ENV Trainer=${Trainer}
RUN echo "Hi, Course is:${Course}, duration is:${Duration} and trainer is:${Trainer}"
CMD ["sleep","1000"]