FROM almalinux:9
ENV course="Devops" \
    duration="120hr" 
ARG trainer="Sivakumar"
ENV trainer=$trainer
RUN echo "Hi, Course is:${course}, duration is:${duration} and trainer is:${trainer}"
CMD ["sleep","1000"]